travis:
  secure:
    BINSTAR_TOKEN: j5SAiwr6bYgjfBqYqHjuHiZn1HCC77Cde5e5rapD0ZIEX+D75ewfUUFfEYxMKpCIhhJimOyrkS82ZWle45e3v6oQ459GYW2RA2xyJ7F+XoDAeJl4X5MnyG4ZZZ6esPC2S11zqZlf2gVqcr/tlPIPmS8ZPMN2WHYghvLm9J/g0g3iP7L2aYqMN8XPbG/JExTMK7rNxuu2k56o5fCA4KjMV/coi9Oml9fx0ZP0BPAsTvqSwFS0NCdP+RZGkTBEa57XsTU1lJp5SQj4Z8i+pIwg59CwZpittORgAiyuzW325bfzjUPRS+Y5aAlul8G/BjMDHW0CeUhs4/Ay1qgUdF4QwmJf5zgq0Z3ZZCgFL5kc9PJcZqDPQAbr4CUNpLFN6oU0OxjmjtgpFTuM788kqcCeCbV/7c0ZkjRkSj5MlPVCtkj7uir4tTVY03wWvqRxE/D3wVF3c88zREmsfutvS0chN1WRNBliIrvxZBqhJ+rei/XMjRx3IbnKfBVqMA7aoWkHu+Kh4f5QdXMiMgTTOsY9KyLZ0JOYvifPKRO5SCA1l8hb5w2gx3AVW5/vn+XKswqSohtSBoa5d+I4LWwwgSweAHEZ4am9br9Hmtm7GKdC1uBIpgYRfaMKxoPZQgQrUYEfUwkvjQHG/E2kEHmWpukIjlNHV9PpWznGSgwbna/3HL4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
